# Generated by Django 4.0.1 on 2022-02-09 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField(blank=True)),
                ('price', models.IntegerField(default=0)),
                ('food_link', models.URLField()),
                ('photo_dish', models.ImageField(upload_to='media/dishes/%Y/%m')),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
